<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EducationalStageFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'group_name' => 'required',
            'status' => 'required|numeric',
        ];
    }

    public function messages()
    {
      //  return parent::messages(); // TODO: Change the autogenerated stub

        return[
          'group_name.required' => 'please select one',
          'status.numeric' => 'please select one '
        ];
    }
}
