<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StudentGroupFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'group_name' => 'required',
            'note'       => 'required',
            'status'     => 'required|numeric',
        ];
    }

    public function messages()
    {
      //  return parent::messages(); // TODO: Change the autogenerated stub
        return [
          'group_name.required' => 'please provide group name',
            'note.required'     => 'please fill the area',
            'status.numeric'   => 'please select the status',
        ];
    }
}
